function writeKml(data)
% NMEA_TO_KML converts a logfile containing NMEA sentences to a KML file.
%
% INPUTS:
%
% * data - data can either be a structue of NMEA messages generated by
% parse_nmea_logfile() or a filename of a NMEA logfile as it then calls
% parse_nmea_logfile() anyway.
%
% OUTPUTS:
% No  explicit function output, but a KML text file is created based on the
% NMEA GGA sentences.

% Check input type
if isstruct(data) %NMEA structure of arrays given.
    Nmea = data;
elseif ischar(data) || isstring(data) % NMEA logfile filename given.
    Nmea = parseNmeaLogfile(data);    
else
    error('Unknown data type for NMEA to KML conversion.')   
end

% Create new kml file
[path, name, ext] = fileparts(Nmea.filename);
kmlName = [name, '.kml'];
overwriteFile = true;
if exist(kmlName,'file')
  promptMessage = sprintf('This file already exists:\n%s\nDo you want to overwrite it?', kmlName);
  titleBarCaption = 'Overwrite?';
  buttonText = questdlg(promptMessage, titleBarCaption, 'Yes', 'No', 'Yes');
  if strcmpi(buttonText, 'No')
    overwriteFile = false;
  end
end
if overwriteFile
  fid = fopen(kmlName, 'wt');
  fprintf('Ovewriting %s file.\n',kmlName)
else
    error('Did not overwrite KML file. Function stopped.')
end

% Write headers to KML file
line_1 = '<?xml version="1.0" encoding="UTF-8"?>\n';
line_2 = '<kml xmlns="http://earth.google.com/kml/2.1">\n';
line_3 = '<Document>\n';
line_4 = '  <Style id="red"><IconStyle><color>ff0000ff</color><scale>.3</scale></IconStyle></Style>\n';
line_5 = '  <Style id="green"><IconStyle><color>ff00ff00</color><scale>.3</scale></IconStyle></Style>\n';
line_6 = '  <Style id="blue"><IconStyle><color>ffff0000</color><scale>.3</scale></IconStyle></Style>\n';
line_7 = '  <Style id="cyan"><IconStyle><color>ffff41b0</color><scale>.3</scale></IconStyle></Style>\n';
fprintf(fid,line_1);
fprintf(fid,line_2);
fprintf(fid,line_3);
fprintf(fid,line_4);
fprintf(fid,line_5);
fprintf(fid,line_6);
fprintf(fid,line_7);

% Write Placemarks to KML file
nPlacemarks = length(Nmea.gga.utcTime);
for i = 1:nPlacemarks
    
    writePlacemark(fid,Nmea,i);  
    
end

fprintf(fid,'</Document>');
fprintf(fid,'</kml>');
    
end
